"""add asset assignment

Revision ID: 723fa54193bf
Revises: 37aba7e04756
Create Date: 2026-09-08 11:50:26.182471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723fa54193bf'
down_revision: Union[str, Sequence[str], None] = '37aba7e04756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'assets', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_assigned_to'), table_name='assets')
    op.drop_column('assets', 'assigned_to')
    # ### end Alembic commands ###
